---
- name: instala java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: installed

- name: remove java 1.7
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: downloads app artifact
  get_url:
    url: https://s3.amazonaws.com/infra-code-workshop/infra-code-workshop-0.1.0.jar
    dest: /tmp/infra-code-workshop-0.1.0.jar

- name: start the application
  shell: "nohup java -jar /tmp/infra-code-workshop-0.1.0.jar &"
